version: '3.8'

services:
  web:
    image: php:8.0-apache
    container_name: php_apache
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: serwer_arch
    volumes:
      - db_data:/var/lib/mysql
      - ./src/users.sql:/docker-entrypoint-initdb.d/users.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: